#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path


SQL_PATTERN = re.compile(r"VALUES \('([^']+)', '([^']*)'\);")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build Epsilon badge metadata from a local badge pack.")
    parser.add_argument("source_dir", type=Path)
    parser.add_argument("--output-json", type=Path, required=True)
    parser.add_argument("--output-sql", type=Path, required=True)
    parser.add_argument("--asset-dir", type=Path)
    parser.add_argument("--copy-assets", action="store_true")
    return parser.parse_args()


def load_required_rights(source_dir: Path) -> dict[str, str]:
    sql_file = source_dir / "badges_21-04-26.sql"
    if not sql_file.exists():
        return {}

    rights: dict[str, str] = {}
    with sql_file.open("r", encoding="utf-8", errors="ignore") as handle:
        for line in handle:
            match = SQL_PATTERN.search(line)
            if not match:
                continue
            badge_code = match.group(1).upper()
            rights[badge_code] = match.group(2).strip()
    return rights


def derive_group(badge_code: str) -> str | None:
    normalized_badge_code = badge_code.upper()

    if normalized_badge_code.startswith("ACH_"):
        return "achievement"
    if normalized_badge_code.startswith("ADM") or normalized_badge_code.startswith("MOD") or normalized_badge_code.startswith("HOBBA"):
        return "staff"
    if normalized_badge_code.startswith("HC") or normalized_badge_code.startswith("CLUB"):
        return "club"

    prefix_match = re.match(r"^([A-Za-z_]+)", badge_code)
    if not prefix_match:
        return None

    prefix = prefix_match.group(1).strip("_").lower()
    return prefix or None


def build_records(source_dir: Path) -> list[dict[str, str | None]]:
    rights_by_code = load_required_rights(source_dir)
    badge_files = sorted(source_dir.glob("*.gif"), key=lambda path: path.name.lower())

    records: list[dict[str, str | None]] = []
    for badge_file in badge_files:
        badge_code = badge_file.stem
        records.append(
            {
                "badgeCode": badge_code,
                "badgeName": badge_code,
                "badgeGroup": derive_group(badge_code),
                "requiredRight": rights_by_code.get(badge_code.upper()) or None,
                "assetPath": f"badges/library/{badge_file.name}",
                "assetKind": "gif",
            }
        )

    return records


def write_json(records: list[dict[str, str | None]], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as handle:
        json.dump(records, handle, separators=(",", ":"), ensure_ascii=True)


def sql_literal(value: str | None) -> str:
    if value is None:
        return "NULL"
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def write_sql(records: list[dict[str, str | None]], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as handle:
        handle.write("-- Generated by tools/importers/badge_catalog_builder.py\n")
        for record in records:
            handle.write(
                "INSERT INTO badge_definitions (badge_code, badge_name, badge_group, required_right, asset_path, asset_kind) "
                f"VALUES ({sql_literal(record['badgeCode'])}, {sql_literal(record['badgeName'])}, "
                f"{sql_literal(record['badgeGroup'])}, {sql_literal(record['requiredRight'])}, "
                f"{sql_literal(record['assetPath'])}, {sql_literal(record['assetKind'])}) "
                "ON CONFLICT (badge_code) DO UPDATE SET "
                "badge_name = EXCLUDED.badge_name, "
                "badge_group = EXCLUDED.badge_group, "
                "required_right = EXCLUDED.required_right, "
                "asset_path = EXCLUDED.asset_path, "
                "asset_kind = EXCLUDED.asset_kind;\n"
            )


def copy_assets(source_dir: Path, asset_dir: Path) -> None:
    asset_dir.mkdir(parents=True, exist_ok=True)
    for badge_file in source_dir.glob("*.gif"):
        shutil.copy2(badge_file, asset_dir / badge_file.name)


def main() -> None:
    args = parse_args()
    records = build_records(args.source_dir)
    write_json(records, args.output_json)
    write_sql(records, args.output_sql)

    if args.copy_assets:
        if args.asset_dir is None:
            raise SystemExit("--copy-assets requires --asset-dir")
        copy_assets(args.source_dir, args.asset_dir)

    print(f"badge_count={len(records)}")


if __name__ == "__main__":
    main()
